import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aahzi Beta",
  description: "Generated by create next app",
};

const RootLayout = ({
    children,
  }: {
    children: React.ReactNode;
  }) =>{
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
